/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowGestionelection (void);
GtkWidget* create_windowAjoutSucc (void);
GtkWidget* create_windowModifSucc (void);
GtkWidget* create_windowSupSucc (void);
GtkWidget* create_windowRemplir (void);
GtkWidget* create_windowID (void);
GtkWidget* create_windowModifierelection (void);
GtkWidget* create_Modifierelection (void);
GtkWidget* create_windowAjoutelection (void);
