/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowGestionelection (void)
{
  GtkWidget *windowGestionelection;
  GtkWidget *fixed1;
  GtkWidget *hseparator1;
  GtkWidget *entryIDrechercher;
  GtkWidget *image57;
  GtkWidget *hseparator2;
  GtkWidget *Rechercherelection;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image35;
  GtkWidget *label120;
  GtkWidget *label186;
  GtkWidget *label195;
  GtkWidget *image86;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeviewRechercher;
  GtkWidget *image88;
  GtkWidget *Afficher;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image46;
  GtkWidget *label126;
  GtkWidget *buttonAjouterelec;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image44;
  GtkWidget *label125;
  GtkWidget *buttonModifierelec;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *buttonSuppelection;
  GtkWidget *alignment41;
  GtkWidget *hbox41;
  GtkWidget *image85;
  GtkWidget *label194;

  windowGestionelection = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowGestionelection, 1000, 600);
  gtk_window_set_title (GTK_WINDOW (windowGestionelection), _("Gestion des elections"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowGestionelection), fixed1);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator1, 208, 16);
  gtk_widget_set_size_request (hseparator1, 16, 16);

  entryIDrechercher = gtk_entry_new ();
  gtk_widget_show (entryIDrechercher);
  gtk_fixed_put (GTK_FIXED (fixed1), entryIDrechercher, 168, 136);
  gtk_widget_set_size_request (entryIDrechercher, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryIDrechercher), 8226);

  image57 = create_pixmap (windowGestionelection, "coul2.png");
  gtk_widget_show (image57);
  gtk_fixed_put (GTK_FIXED (fixed1), image57, 688, 616);
  gtk_widget_set_size_request (image57, 157, 40);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator2, 192, 184);
  gtk_widget_set_size_request (hseparator2, 16, 16);

  Rechercherelection = gtk_button_new ();
  gtk_widget_show (Rechercherelection);
  gtk_fixed_put (GTK_FIXED (fixed1), Rechercherelection, 8, 200);
  gtk_widget_set_size_request (Rechercherelection, 224, 40);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (Rechercherelection), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image35 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox30), image35, FALSE, FALSE, 0);

  label120 = gtk_label_new_with_mnemonic (_("                                    Rechercher"));
  gtk_widget_show (label120);
  gtk_box_pack_start (GTK_BOX (hbox30), label120, FALSE, FALSE, 0);

  label186 = gtk_label_new (_("<span color=\"purple\"><b> Chercher une election</b></span>\n Donner la Municipalite"));
  gtk_widget_show (label186);
  gtk_fixed_put (GTK_FIXED (fixed1), label186, 0, 128);
  gtk_widget_set_size_request (label186, 176, 32);
  gtk_label_set_use_markup (GTK_LABEL (label186), TRUE);

  label195 = gtk_label_new (_("<span color=\"purple\" font-size=\"19000\"><b> Gestion Des Elections</b></span>"));
  gtk_widget_show (label195);
  gtk_fixed_put (GTK_FIXED (fixed1), label195, 272, 8);
  gtk_widget_set_size_request (label195, 392, 64);
  gtk_label_set_use_markup (GTK_LABEL (label195), TRUE);

  image86 = create_pixmap (windowGestionelection, "electionnn.png");
  gtk_widget_show (image86);
  gtk_fixed_put (GTK_FIXED (fixed1), image86, 760, 0);
  gtk_widget_set_size_request (image86, 216, 104);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_fixed_put (GTK_FIXED (fixed1), scrolledwindow5, 360, 144);
  gtk_widget_set_size_request (scrolledwindow5, 616, 264);

  treeviewRechercher = gtk_tree_view_new ();
  gtk_widget_show (treeviewRechercher);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeviewRechercher);

  image88 = create_pixmap (windowGestionelection, "ElectionBackground1.jpg");
  gtk_widget_show (image88);
  gtk_fixed_put (GTK_FIXED (fixed1), image88, 320, 96);
  gtk_widget_set_size_request (image88, 680, 392);

  Afficher = gtk_button_new ();
  gtk_widget_show (Afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), Afficher, 568, 408);
  gtk_widget_set_size_request (Afficher, 184, 48);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (Afficher), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image46 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image46);
  gtk_box_pack_start (GTK_BOX (hbox33), image46, FALSE, FALSE, 0);

  label126 = gtk_label_new_with_mnemonic (_("Afficher "));
  gtk_widget_show (label126);
  gtk_box_pack_start (GTK_BOX (hbox33), label126, FALSE, FALSE, 0);

  buttonAjouterelec = gtk_button_new ();
  gtk_widget_show (buttonAjouterelec);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAjouterelec, 16, 256);
  gtk_widget_set_size_request (buttonAjouterelec, 128, 48);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (buttonAjouterelec), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image44 = create_pixmap (windowGestionelection, "addEmp.png");
  gtk_widget_show (image44);
  gtk_box_pack_start (GTK_BOX (hbox32), image44, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (image44), 0, 0.5);

  label125 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label125);
  gtk_box_pack_start (GTK_BOX (hbox32), label125, FALSE, FALSE, 0);

  buttonModifierelec = gtk_button_new ();
  gtk_widget_show (buttonModifierelec);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonModifierelec, 16, 312);
  gtk_widget_set_size_request (buttonModifierelec, 128, 48);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonModifierelec), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = create_pixmap (windowGestionelection, "settings.png");
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_(" Modifier "));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  buttonSuppelection = gtk_button_new ();
  gtk_widget_show (buttonSuppelection);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonSuppelection, 16, 376);
  gtk_widget_set_size_request (buttonSuppelection, 128, 48);

  alignment41 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment41);
  gtk_container_add (GTK_CONTAINER (buttonSuppelection), alignment41);

  hbox41 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox41);
  gtk_container_add (GTK_CONTAINER (alignment41), hbox41);

  image85 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image85);
  gtk_box_pack_start (GTK_BOX (hbox41), image85, FALSE, FALSE, 0);

  label194 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label194);
  gtk_box_pack_start (GTK_BOX (hbox41), label194, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) Rechercherelection, "clicked",
                    G_CALLBACK (on_Rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewRechercher, "row_activated",
                    G_CALLBACK (on_treeviewRechercher_row_activated),
                    NULL);
  g_signal_connect ((gpointer) Afficher, "clicked",
                    G_CALLBACK (on_Afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAjouterelec, "clicked",
                    G_CALLBACK (on_buttonAjoutelec_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifierelec, "clicked",
                    G_CALLBACK (on_buttonModifelec_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSuppelection, "clicked",
                    G_CALLBACK (on_buttonSuppelection_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionelection, windowGestionelection, "windowGestionelection");
  GLADE_HOOKUP_OBJECT (windowGestionelection, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowGestionelection, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (windowGestionelection, entryIDrechercher, "entryIDrechercher");
  GLADE_HOOKUP_OBJECT (windowGestionelection, image57, "image57");
  GLADE_HOOKUP_OBJECT (windowGestionelection, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (windowGestionelection, Rechercherelection, "Rechercherelection");
  GLADE_HOOKUP_OBJECT (windowGestionelection, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (windowGestionelection, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (windowGestionelection, image35, "image35");
  GLADE_HOOKUP_OBJECT (windowGestionelection, label120, "label120");
  GLADE_HOOKUP_OBJECT (windowGestionelection, label186, "label186");
  GLADE_HOOKUP_OBJECT (windowGestionelection, label195, "label195");
  GLADE_HOOKUP_OBJECT (windowGestionelection, image86, "image86");
  GLADE_HOOKUP_OBJECT (windowGestionelection, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (windowGestionelection, treeviewRechercher, "treeviewRechercher");
  GLADE_HOOKUP_OBJECT (windowGestionelection, image88, "image88");
  GLADE_HOOKUP_OBJECT (windowGestionelection, Afficher, "Afficher");
  GLADE_HOOKUP_OBJECT (windowGestionelection, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (windowGestionelection, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (windowGestionelection, image46, "image46");
  GLADE_HOOKUP_OBJECT (windowGestionelection, label126, "label126");
  GLADE_HOOKUP_OBJECT (windowGestionelection, buttonAjouterelec, "buttonAjouterelec");
  GLADE_HOOKUP_OBJECT (windowGestionelection, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (windowGestionelection, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (windowGestionelection, image44, "image44");
  GLADE_HOOKUP_OBJECT (windowGestionelection, label125, "label125");
  GLADE_HOOKUP_OBJECT (windowGestionelection, buttonModifierelec, "buttonModifierelec");
  GLADE_HOOKUP_OBJECT (windowGestionelection, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowGestionelection, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowGestionelection, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowGestionelection, label4, "label4");
  GLADE_HOOKUP_OBJECT (windowGestionelection, buttonSuppelection, "buttonSuppelection");
  GLADE_HOOKUP_OBJECT (windowGestionelection, alignment41, "alignment41");
  GLADE_HOOKUP_OBJECT (windowGestionelection, hbox41, "hbox41");
  GLADE_HOOKUP_OBJECT (windowGestionelection, image85, "image85");
  GLADE_HOOKUP_OBJECT (windowGestionelection, label194, "label194");

  return windowGestionelection;
}

GtkWidget*
create_windowAjoutSucc (void)
{
  GtkWidget *windowAjoutSucc;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed7;
  GtkWidget *image39;
  GtkWidget *label33;
  GtkWidget *dialog_action_area1;
  GtkWidget *okbutton1;

  windowAjoutSucc = gtk_dialog_new ();
  gtk_widget_set_size_request (windowAjoutSucc, 310, 200);
  gtk_window_set_type_hint (GTK_WINDOW (windowAjoutSucc), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (windowAjoutSucc), FALSE);

  dialog_vbox1 = GTK_DIALOG (windowAjoutSucc)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed7, TRUE, TRUE, 0);

  image39 = create_pixmap (windowAjoutSucc, "check(2).png");
  gtk_widget_show (image39);
  gtk_fixed_put (GTK_FIXED (fixed7), image39, 128, 32);
  gtk_widget_set_size_request (image39, 56, 48);

  label33 = gtk_label_new_with_mnemonic (_("<span foreground=\"#f936\" ><b>Election ajout\303\251 avec succ\303\251e</b></span>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed7), label33, 40, 56);
  gtk_widget_set_size_request (label33, 232, 112);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  dialog_action_area1 = GTK_DIALOG (windowAjoutSucc)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (windowAjoutSucc), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAjoutSucc, windowAjoutSucc, "windowAjoutSucc");
  GLADE_HOOKUP_OBJECT_NO_REF (windowAjoutSucc, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (windowAjoutSucc, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (windowAjoutSucc, image39, "image39");
  GLADE_HOOKUP_OBJECT (windowAjoutSucc, label33, "label33");
  GLADE_HOOKUP_OBJECT_NO_REF (windowAjoutSucc, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (windowAjoutSucc, okbutton1, "okbutton1");

  return windowAjoutSucc;
}

GtkWidget*
create_windowModifSucc (void)
{
  GtkWidget *windowModifSucc;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed8;
  GtkWidget *label34;
  GtkWidget *image40;
  GtkWidget *dialog_action_area2;
  GtkWidget *okbutton2;

  windowModifSucc = gtk_dialog_new ();
  gtk_widget_set_size_request (windowModifSucc, 310, 200);
  gtk_window_set_type_hint (GTK_WINDOW (windowModifSucc), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (windowModifSucc), FALSE);

  dialog_vbox2 = GTK_DIALOG (windowModifSucc)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed8, TRUE, TRUE, 0);

  label34 = gtk_label_new_with_mnemonic (_("<span foreground=\"#f936\" ><b>Election modifi\303\251 avec succ\303\251e</b></span>"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed8), label34, 40, 72);
  gtk_widget_set_size_request (label34, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  image40 = create_pixmap (windowModifSucc, "check(2).png");
  gtk_widget_show (image40);
  gtk_fixed_put (GTK_FIXED (fixed8), image40, 120, 32);
  gtk_widget_set_size_request (image40, 64, 56);

  dialog_action_area2 = GTK_DIALOG (windowModifSucc)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (windowModifSucc), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) okbutton2, "clicked",
                    G_CALLBACK (on_okbutton2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowModifSucc, windowModifSucc, "windowModifSucc");
  GLADE_HOOKUP_OBJECT_NO_REF (windowModifSucc, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (windowModifSucc, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (windowModifSucc, label34, "label34");
  GLADE_HOOKUP_OBJECT (windowModifSucc, image40, "image40");
  GLADE_HOOKUP_OBJECT_NO_REF (windowModifSucc, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (windowModifSucc, okbutton2, "okbutton2");

  return windowModifSucc;
}

GtkWidget*
create_windowSupSucc (void)
{
  GtkWidget *windowSupSucc;
  GtkWidget *dialog_vbox3;
  GtkWidget *fixed9;
  GtkWidget *image74;
  GtkWidget *label35;
  GtkWidget *dialog_action_area3;
  GtkWidget *okbutton3;

  windowSupSucc = gtk_dialog_new ();
  gtk_widget_set_size_request (windowSupSucc, 310, 200);
  gtk_window_set_type_hint (GTK_WINDOW (windowSupSucc), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (windowSupSucc), FALSE);

  dialog_vbox3 = GTK_DIALOG (windowSupSucc)->vbox;
  gtk_widget_show (dialog_vbox3);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), fixed9, TRUE, TRUE, 0);

  image74 = create_pixmap (windowSupSucc, "deleteEmp.png");
  gtk_widget_show (image74);
  gtk_fixed_put (GTK_FIXED (fixed9), image74, 120, 40);
  gtk_widget_set_size_request (image74, 64, 56);

  label35 = gtk_label_new_with_mnemonic (_("<span foreground = '#2020' ><b> Election supprimer avec succ\303\251s </b> </span>"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed9), label35, 40, 88);
  gtk_widget_set_size_request (label35, 225, 40);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  dialog_action_area3 = GTK_DIALOG (windowSupSucc)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  okbutton3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (windowSupSucc), okbutton3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton3, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) okbutton3, "clicked",
                    G_CALLBACK (on_okbutton3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowSupSucc, windowSupSucc, "windowSupSucc");
  GLADE_HOOKUP_OBJECT_NO_REF (windowSupSucc, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (windowSupSucc, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (windowSupSucc, image74, "image74");
  GLADE_HOOKUP_OBJECT (windowSupSucc, label35, "label35");
  GLADE_HOOKUP_OBJECT_NO_REF (windowSupSucc, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (windowSupSucc, okbutton3, "okbutton3");

  return windowSupSucc;
}

GtkWidget*
create_windowRemplir (void)
{
  GtkWidget *windowRemplir;
  GtkWidget *dialog_vbox4;
  GtkWidget *fixed10;
  GtkWidget *image38;
  GtkWidget *label36;
  GtkWidget *dialog_action_area4;
  GtkWidget *okbutton444;

  windowRemplir = gtk_dialog_new ();
  gtk_widget_set_size_request (windowRemplir, 310, 200);
  gtk_window_set_type_hint (GTK_WINDOW (windowRemplir), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (windowRemplir), FALSE);

  dialog_vbox4 = GTK_DIALOG (windowRemplir)->vbox;
  gtk_widget_show (dialog_vbox4);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), fixed10, TRUE, TRUE, 0);

  image38 = create_pixmap (windowRemplir, "warning(3).png");
  gtk_widget_show (image38);
  gtk_fixed_put (GTK_FIXED (fixed10), image38, 104, 24);
  gtk_widget_set_size_request (image38, 96, 80);

  label36 = gtk_label_new (_("<span foreground=\"#FF0404\" ><b>Veuillez remplir tous les champs !</b></span>"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed10), label36, 32, 96);
  gtk_widget_set_size_request (label36, 235, 40);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  dialog_action_area4 = GTK_DIALOG (windowRemplir)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  okbutton444 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton444);
  gtk_dialog_add_action_widget (GTK_DIALOG (windowRemplir), okbutton444, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton444, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) okbutton444, "clicked",
                    G_CALLBACK (on_okbutton444_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowRemplir, windowRemplir, "windowRemplir");
  GLADE_HOOKUP_OBJECT_NO_REF (windowRemplir, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (windowRemplir, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (windowRemplir, image38, "image38");
  GLADE_HOOKUP_OBJECT (windowRemplir, label36, "label36");
  GLADE_HOOKUP_OBJECT_NO_REF (windowRemplir, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (windowRemplir, okbutton444, "okbutton444");

  return windowRemplir;
}

GtkWidget*
create_windowID (void)
{
  GtkWidget *windowID;
  GtkWidget *vbox1;
  GtkWidget *fixed12;
  GtkWidget *image37;
  GtkWidget *label190;
  GtkWidget *label124;
  GtkWidget *hbuttonbox3;
  GtkWidget *button24;

  windowID = gtk_dialog_new ();
  gtk_widget_set_size_request (windowID, 310, 200);
  gtk_window_set_type_hint (GTK_WINDOW (windowID), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (windowID), FALSE);

  vbox1 = GTK_DIALOG (windowID)->vbox;
  gtk_widget_show (vbox1);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_box_pack_start (GTK_BOX (vbox1), fixed12, TRUE, TRUE, 0);

  image37 = create_pixmap (windowID, "warning(3).png");
  gtk_widget_show (image37);
  gtk_fixed_put (GTK_FIXED (fixed12), image37, 112, 8);
  gtk_widget_set_size_request (image37, 64, 64);

  label190 = gtk_label_new_with_mnemonic (_("<span foreground=\"#FF0404\" ><b>ID existe d\303\251ja ! </b></span>"));
  gtk_widget_show (label190);
  gtk_fixed_put (GTK_FIXED (fixed12), label190, 88, 72);
  gtk_widget_set_size_request (label190, 120, 48);
  gtk_label_set_use_markup (GTK_LABEL (label190), TRUE);

  label124 = gtk_label_new_with_mnemonic (_("<span foreground=\"#FF0404\" ><b> veuillez entrez un nouveau </b></span>"));
  gtk_widget_show (label124);
  gtk_fixed_put (GTK_FIXED (fixed12), label124, 0, 72);
  gtk_widget_set_size_request (label124, 296, 112);
  gtk_label_set_use_markup (GTK_LABEL (label124), TRUE);

  hbuttonbox3 = GTK_DIALOG (windowID)->action_area;
  gtk_widget_show (hbuttonbox3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_END);

  button24 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button24);
  gtk_dialog_add_action_widget (GTK_DIALOG (windowID), button24, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button24, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button24, "clicked",
                    G_CALLBACK (on_button24_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowID, windowID, "windowID");
  GLADE_HOOKUP_OBJECT_NO_REF (windowID, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (windowID, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (windowID, image37, "image37");
  GLADE_HOOKUP_OBJECT (windowID, label190, "label190");
  GLADE_HOOKUP_OBJECT (windowID, label124, "label124");
  GLADE_HOOKUP_OBJECT_NO_REF (windowID, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (windowID, button24, "button24");

  return windowID;
}

GtkWidget*
create_windowModifierelection (void)
{
  GtkWidget *windowModifierelection;
  GtkWidget *fixed13;
  GtkWidget *entryIDMODIF;
  GtkWidget *buttonAcceuil3;
  GtkWidget *alignment36;
  GtkWidget *hbox36;
  GtkWidget *image78;
  GtkWidget *label150;
  GtkWidget *scrolledwindow7;
  GtkWidget *treeview1;
  GtkWidget *buttonRechercherMODIF;
  GtkWidget *alignment34;
  GtkWidget *hbox34;
  GtkWidget *image76;
  GtkWidget *label147;
  GtkWidget *buttonModiff;
  GtkWidget *alignment35;
  GtkWidget *hbox35;
  GtkWidget *image77;
  GtkWidget *label149;
  GtkWidget *label146;

  windowModifierelection = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowModifierelection), _("Modifier election"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (windowModifierelection), fixed13);

  entryIDMODIF = gtk_entry_new ();
  gtk_widget_show (entryIDMODIF);
  gtk_fixed_put (GTK_FIXED (fixed13), entryIDMODIF, 392, 136);
  gtk_widget_set_size_request (entryIDMODIF, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryIDMODIF), 8226);

  buttonAcceuil3 = gtk_button_new ();
  gtk_widget_show (buttonAcceuil3);
  gtk_fixed_put (GTK_FIXED (fixed13), buttonAcceuil3, 8, 8);
  gtk_widget_set_size_request (buttonAcceuil3, 104, 32);

  alignment36 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment36);
  gtk_container_add (GTK_CONTAINER (buttonAcceuil3), alignment36);

  hbox36 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox36);
  gtk_container_add (GTK_CONTAINER (alignment36), hbox36);

  image78 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image78);
  gtk_box_pack_start (GTK_BOX (hbox36), image78, FALSE, FALSE, 0);

  label150 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label150);
  gtk_box_pack_start (GTK_BOX (hbox36), label150, FALSE, FALSE, 0);

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow7);
  gtk_fixed_put (GTK_FIXED (fixed13), scrolledwindow7, 40, 104);
  gtk_widget_set_size_request (scrolledwindow7, 320, 152);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), treeview1);
  gtk_widget_set_size_request (treeview1, 320, 152);

  buttonRechercherMODIF = gtk_button_new ();
  gtk_widget_show (buttonRechercherMODIF);
  gtk_fixed_put (GTK_FIXED (fixed13), buttonRechercherMODIF, 592, 136);
  gtk_widget_set_size_request (buttonRechercherMODIF, 64, 32);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (buttonRechercherMODIF), alignment34);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox34);

  image76 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image76);
  gtk_box_pack_start (GTK_BOX (hbox34), image76, FALSE, FALSE, 0);

  label147 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label147);
  gtk_box_pack_start (GTK_BOX (hbox34), label147, FALSE, FALSE, 0);

  buttonModiff = gtk_button_new ();
  gtk_widget_show (buttonModiff);
  gtk_fixed_put (GTK_FIXED (fixed13), buttonModiff, 472, 184);
  gtk_widget_set_size_request (buttonModiff, 130, 40);

  alignment35 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment35);
  gtk_container_add (GTK_CONTAINER (buttonModiff), alignment35);

  hbox35 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox35);
  gtk_container_add (GTK_CONTAINER (alignment35), hbox35);

  image77 = create_pixmap (windowModifierelection, "editEmp.png");
  gtk_widget_show (image77);
  gtk_box_pack_start (GTK_BOX (hbox35), image77, FALSE, FALSE, 0);

  label149 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label149);
  gtk_box_pack_start (GTK_BOX (hbox35), label149, FALSE, FALSE, 0);

  label146 = gtk_label_new (_("<span color=\"purple\"><b>ENTREZ L'ID D'ELECTION A MODIFIER  !</b></span>"));
  gtk_widget_show (label146);
  gtk_fixed_put (GTK_FIXED (fixed13), label146, 192, 40);
  gtk_widget_set_size_request (label146, 440, 48);
  gtk_label_set_use_markup (GTK_LABEL (label146), TRUE);

  g_signal_connect ((gpointer) buttonAcceuil3, "clicked",
                    G_CALLBACK (on_buttonAcceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "start_interactive_search",
                    G_CALLBACK (on_treeview_start_interactive_search),
                    NULL);
  g_signal_connect ((gpointer) buttonRechercherMODIF, "clicked",
                    G_CALLBACK (on_buttonRechercherMODIF_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModiff, "clicked",
                    G_CALLBACK (on_buttonModifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowModifierelection, windowModifierelection, "windowModifierelection");
  GLADE_HOOKUP_OBJECT (windowModifierelection, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (windowModifierelection, entryIDMODIF, "entryIDMODIF");
  GLADE_HOOKUP_OBJECT (windowModifierelection, buttonAcceuil3, "buttonAcceuil3");
  GLADE_HOOKUP_OBJECT (windowModifierelection, alignment36, "alignment36");
  GLADE_HOOKUP_OBJECT (windowModifierelection, hbox36, "hbox36");
  GLADE_HOOKUP_OBJECT (windowModifierelection, image78, "image78");
  GLADE_HOOKUP_OBJECT (windowModifierelection, label150, "label150");
  GLADE_HOOKUP_OBJECT (windowModifierelection, scrolledwindow7, "scrolledwindow7");
  GLADE_HOOKUP_OBJECT (windowModifierelection, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (windowModifierelection, buttonRechercherMODIF, "buttonRechercherMODIF");
  GLADE_HOOKUP_OBJECT (windowModifierelection, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (windowModifierelection, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (windowModifierelection, image76, "image76");
  GLADE_HOOKUP_OBJECT (windowModifierelection, label147, "label147");
  GLADE_HOOKUP_OBJECT (windowModifierelection, buttonModiff, "buttonModiff");
  GLADE_HOOKUP_OBJECT (windowModifierelection, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (windowModifierelection, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (windowModifierelection, image77, "image77");
  GLADE_HOOKUP_OBJECT (windowModifierelection, label149, "label149");
  GLADE_HOOKUP_OBJECT (windowModifierelection, label146, "label146");

  return windowModifierelection;
}

GtkWidget*
create_Modifierelection (void)
{
  GtkWidget *Modifierelection;
  GtkWidget *fixed14;
  GtkWidget *entryMOdifierId;
  GtkObject *spinbuttonJours_adj;
  GtkWidget *spinbuttonJours;
  GtkObject *spinbuttonMois_adj;
  GtkWidget *spinbuttonMois;
  GtkObject *spinbuttonAnnees_adj;
  GtkWidget *spinbuttonAnnees;
  GtkWidget *label166;
  GtkWidget *label167;
  GtkWidget *combobox2nbc;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton5;
  GtkWidget *checkbutton6;
  GtkWidget *checkbutton7;
  GtkWidget *label161;
  GtkWidget *label196;
  GtkWidget *label198;
  GtkWidget *label199;
  GtkWidget *label155;
  GtkWidget *label192;
  GtkWidget *label193;
  GtkWidget *label200;
  GtkWidget *image87;
  GtkWidget *buttonConfirmerModif;
  GtkWidget *comboboxmuni;

  Modifierelection = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modifierelection), _("Modifier Election"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (Modifierelection), fixed14);

  entryMOdifierId = gtk_entry_new ();
  gtk_widget_show (entryMOdifierId);
  gtk_fixed_put (GTK_FIXED (fixed14), entryMOdifierId, 136, 72);
  gtk_widget_set_size_request (entryMOdifierId, 144, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryMOdifierId), 8226);

  spinbuttonJours_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonJours = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJours_adj), 1, 0);
  gtk_widget_show (spinbuttonJours);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbuttonJours, 88, 256);
  gtk_widget_set_size_request (spinbuttonJours, 80, 25);

  spinbuttonMois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonMois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMois_adj), 1, 0);
  gtk_widget_show (spinbuttonMois);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbuttonMois, 232, 256);
  gtk_widget_set_size_request (spinbuttonMois, 80, 25);

  spinbuttonAnnees_adj = gtk_adjustment_new (2021, 1990, 2030, 1, 10, 10);
  spinbuttonAnnees = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAnnees_adj), 1, 0);
  gtk_widget_show (spinbuttonAnnees);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbuttonAnnees, 384, 256);
  gtk_widget_set_size_request (spinbuttonAnnees, 80, 25);

  label166 = gtk_label_new ("");
  gtk_widget_show (label166);
  gtk_fixed_put (GTK_FIXED (fixed14), label166, 480, 192);
  gtk_widget_set_size_request (label166, 73, 17);
  gtk_label_set_use_markup (GTK_LABEL (label166), TRUE);

  label167 = gtk_label_new (_("<span color=\"purple\" ><b>Municipalit\303\251 : </b></span>"));
  gtk_widget_show (label167);
  gtk_fixed_put (GTK_FIXED (fixed14), label167, 8, 120);
  gtk_widget_set_size_request (label167, 136, 40);
  gtk_label_set_use_markup (GTK_LABEL (label167), TRUE);

  combobox2nbc = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2nbc);
  gtk_fixed_put (GTK_FIXED (fixed14), combobox2nbc, 424, 120);
  gtk_widget_set_size_request (combobox2nbc, 144, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2nbc), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2nbc), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2nbc), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2nbc), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2nbc), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2nbc), _("40"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2nbc), _("60"));

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("5000"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed14), checkbutton1, 640, 160);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("5001 a 10.000"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed14), checkbutton2, 640, 192);
  gtk_widget_set_size_request (checkbutton2, 128, 24);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("10.001 a 25.001"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed14), checkbutton3, 640, 224);
  gtk_widget_set_size_request (checkbutton3, 192, 24);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("25.001 a 50.000"));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed14), checkbutton4, 640, 256);
  gtk_widget_set_size_request (checkbutton4, 144, 24);

  checkbutton5 = gtk_check_button_new_with_mnemonic (_("50.001 a 100.000"));
  gtk_widget_show (checkbutton5);
  gtk_fixed_put (GTK_FIXED (fixed14), checkbutton5, 640, 288);
  gtk_widget_set_size_request (checkbutton5, 160, 24);

  checkbutton6 = gtk_check_button_new_with_mnemonic (_("100.001 a 500.000"));
  gtk_widget_show (checkbutton6);
  gtk_fixed_put (GTK_FIXED (fixed14), checkbutton6, 640, 320);
  gtk_widget_set_size_request (checkbutton6, 160, 24);

  checkbutton7 = gtk_check_button_new_with_mnemonic (_("plus que 500.000 "));
  gtk_widget_show (checkbutton7);
  gtk_fixed_put (GTK_FIXED (fixed14), checkbutton7, 640, 352);
  gtk_widget_set_size_request (checkbutton7, 144, 24);

  label161 = gtk_label_new (_("<span color=\"purple\" ><b>Date de l'elections : </b></span>"));
  gtk_widget_show (label161);
  gtk_fixed_put (GTK_FIXED (fixed14), label161, 16, 216);
  gtk_widget_set_size_request (label161, 168, 40);
  gtk_label_set_use_markup (GTK_LABEL (label161), TRUE);

  label196 = gtk_label_new (_("Jour"));
  gtk_widget_show (label196);
  gtk_fixed_put (GTK_FIXED (fixed14), label196, 24, 264);
  gtk_widget_set_size_request (label196, 57, 17);

  label198 = gtk_label_new (_("Mois"));
  gtk_widget_show (label198);
  gtk_fixed_put (GTK_FIXED (fixed14), label198, 168, 264);
  gtk_widget_set_size_request (label198, 57, 17);

  label199 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label199);
  gtk_fixed_put (GTK_FIXED (fixed14), label199, 320, 264);
  gtk_widget_set_size_request (label199, 57, 17);

  label155 = gtk_label_new (_("<span color=\"purple\" ><b>Chercher l'ID : </b></span>"));
  gtk_widget_show (label155);
  gtk_fixed_put (GTK_FIXED (fixed14), label155, 16, 64);
  gtk_widget_set_size_request (label155, 128, 40);
  gtk_label_set_use_markup (GTK_LABEL (label155), TRUE);

  label192 = gtk_label_new (_("<span color=\"purple\"><b>Nb Conseillers</b></span>"));
  gtk_widget_show (label192);
  gtk_fixed_put (GTK_FIXED (fixed14), label192, 304, 120);
  gtk_widget_set_size_request (label192, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (label192), TRUE);

  label193 = gtk_label_new (_("<span color=\"purple\"><b>Nb des habitants :</b></span>"));
  gtk_widget_show (label193);
  gtk_fixed_put (GTK_FIXED (fixed14), label193, 624, 120);
  gtk_widget_set_size_request (label193, 224, 32);
  gtk_label_set_use_markup (GTK_LABEL (label193), TRUE);

  label200 = gtk_label_new (_("<span color=\"brown\" font-size=\"19000\"><b>Modification des Elections :</b></span>"));
  gtk_widget_show (label200);
  gtk_fixed_put (GTK_FIXED (fixed14), label200, 248, 8);
  gtk_widget_set_size_request (label200, 360, 72);
  gtk_label_set_use_markup (GTK_LABEL (label200), TRUE);

  image87 = create_pixmap (Modifierelection, "electionnn.png");
  gtk_widget_show (image87);
  gtk_fixed_put (GTK_FIXED (fixed14), image87, 704, 16);
  gtk_widget_set_size_request (image87, 152, 96);

  buttonConfirmerModif = gtk_button_new_from_stock ("Modifier");
  gtk_widget_show (buttonConfirmerModif);
  gtk_fixed_put (GTK_FIXED (fixed14), buttonConfirmerModif, 352, 336);
  gtk_widget_set_size_request (buttonConfirmerModif, 168, 48);
  gtk_container_set_border_width (GTK_CONTAINER (buttonConfirmerModif), 1);

  comboboxmuni = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxmuni);
  gtk_fixed_put (GTK_FIXED (fixed14), comboboxmuni, 128, 120);
  gtk_widget_set_size_request (comboboxmuni, 144, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmuni), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmuni), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmuni), _("Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmuni), _("Hammamet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmuni), _("Ben arous"));

  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3, "toggled",
                    G_CALLBACK (on_checkbutton7_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton4, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton5, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton6, "toggled",
                    G_CALLBACK (on_checkbutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton7, "toggled",
                    G_CALLBACK (on_checkbutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonConfirmerModif, "clicked",
                    G_CALLBACK (on_buttonConfirmerModifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifierelection, Modifierelection, "Modifierelection");
  GLADE_HOOKUP_OBJECT (Modifierelection, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (Modifierelection, entryMOdifierId, "entryMOdifierId");
  GLADE_HOOKUP_OBJECT (Modifierelection, spinbuttonJours, "spinbuttonJours");
  GLADE_HOOKUP_OBJECT (Modifierelection, spinbuttonMois, "spinbuttonMois");
  GLADE_HOOKUP_OBJECT (Modifierelection, spinbuttonAnnees, "spinbuttonAnnees");
  GLADE_HOOKUP_OBJECT (Modifierelection, label166, "label166");
  GLADE_HOOKUP_OBJECT (Modifierelection, label167, "label167");
  GLADE_HOOKUP_OBJECT (Modifierelection, combobox2nbc, "combobox2nbc");
  GLADE_HOOKUP_OBJECT (Modifierelection, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (Modifierelection, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (Modifierelection, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (Modifierelection, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (Modifierelection, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (Modifierelection, checkbutton6, "checkbutton6");
  GLADE_HOOKUP_OBJECT (Modifierelection, checkbutton7, "checkbutton7");
  GLADE_HOOKUP_OBJECT (Modifierelection, label161, "label161");
  GLADE_HOOKUP_OBJECT (Modifierelection, label196, "label196");
  GLADE_HOOKUP_OBJECT (Modifierelection, label198, "label198");
  GLADE_HOOKUP_OBJECT (Modifierelection, label199, "label199");
  GLADE_HOOKUP_OBJECT (Modifierelection, label155, "label155");
  GLADE_HOOKUP_OBJECT (Modifierelection, label192, "label192");
  GLADE_HOOKUP_OBJECT (Modifierelection, label193, "label193");
  GLADE_HOOKUP_OBJECT (Modifierelection, label200, "label200");
  GLADE_HOOKUP_OBJECT (Modifierelection, image87, "image87");
  GLADE_HOOKUP_OBJECT (Modifierelection, buttonConfirmerModif, "buttonConfirmerModif");
  GLADE_HOOKUP_OBJECT (Modifierelection, comboboxmuni, "comboboxmuni");

  return Modifierelection;
}

GtkWidget*
create_windowAjoutelection (void)
{
  GtkWidget *windowAjoutelection;
  GtkWidget *fixed15;
  GtkWidget *entryId;
  GtkObject *spinbuttonSkJours_adj;
  GtkWidget *spinbuttonSkJours;
  GtkObject *spinbuttonSkMois_adj;
  GtkWidget *spinbuttonSkMois;
  GtkObject *spinbuttonSkAnnees_adj;
  GtkWidget *spinbuttonSkAnnees;
  GtkWidget *buttonMenu;
  GtkWidget *alignment40;
  GtkWidget *hbox40;
  GtkWidget *image84;
  GtkWidget *label180;
  GtkWidget *buttonAjouter;
  GtkWidget *alignment38;
  GtkWidget *hbox38;
  GtkWidget *image82;
  GtkWidget *label178;
  GtkWidget *_;
  GtkWidget *alignment39;
  GtkWidget *hbox39;
  GtkWidget *image83;
  GtkWidget *label179;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton4;
  GtkWidget *radiobutton5;
  GtkWidget *radiobutton6;
  GtkWidget *radiobutton7;
  GtkWidget *label171;
  GtkWidget *label173;
  GtkWidget *label172;
  GtkWidget *label175;
  GtkWidget *radiobutton2;
  GtkWidget *label191;
  GtkWidget *label201;
  GtkWidget *comboboxnbc;
  GtkWidget *comboboxnbh;

  windowAjoutelection = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowAjoutelection), _("Ajout election"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (windowAjoutelection), fixed15);

  entryId = gtk_entry_new ();
  gtk_widget_show (entryId);
  gtk_fixed_put (GTK_FIXED (fixed15), entryId, 120, 72);
  gtk_widget_set_size_request (entryId, 128, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryId), 8226);

  spinbuttonSkJours_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonSkJours = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonSkJours_adj), 1, 0);
  gtk_widget_show (spinbuttonSkJours);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbuttonSkJours, 200, 160);
  gtk_widget_set_size_request (spinbuttonSkJours, 80, 24);

  spinbuttonSkMois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonSkMois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonSkMois_adj), 1, 0);
  gtk_widget_show (spinbuttonSkMois);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbuttonSkMois, 304, 160);
  gtk_widget_set_size_request (spinbuttonSkMois, 80, 24);

  spinbuttonSkAnnees_adj = gtk_adjustment_new (2021, 1990, 2030, 1, 10, 10);
  spinbuttonSkAnnees = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonSkAnnees_adj), 1, 0);
  gtk_widget_show (spinbuttonSkAnnees);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbuttonSkAnnees, 408, 160);
  gtk_widget_set_size_request (spinbuttonSkAnnees, 80, 24);

  buttonMenu = gtk_button_new ();
  gtk_widget_show (buttonMenu);
  gtk_fixed_put (GTK_FIXED (fixed15), buttonMenu, 640, 248);
  gtk_widget_set_size_request (buttonMenu, 144, 32);

  alignment40 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment40);
  gtk_container_add (GTK_CONTAINER (buttonMenu), alignment40);

  hbox40 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox40);
  gtk_container_add (GTK_CONTAINER (alignment40), hbox40);

  image84 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image84);
  gtk_box_pack_start (GTK_BOX (hbox40), image84, FALSE, FALSE, 0);

  label180 = gtk_label_new_with_mnemonic (_("MENU"));
  gtk_widget_show (label180);
  gtk_box_pack_start (GTK_BOX (hbox40), label180, FALSE, FALSE, 0);

  buttonAjouter = gtk_button_new ();
  gtk_widget_show (buttonAjouter);
  gtk_fixed_put (GTK_FIXED (fixed15), buttonAjouter, 640, 288);
  gtk_widget_set_size_request (buttonAjouter, 144, 32);

  alignment38 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment38);
  gtk_container_add (GTK_CONTAINER (buttonAjouter), alignment38);

  hbox38 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox38);
  gtk_container_add (GTK_CONTAINER (alignment38), hbox38);

  image82 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image82);
  gtk_box_pack_start (GTK_BOX (hbox38), image82, FALSE, FALSE, 0);

  label178 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label178);
  gtk_box_pack_start (GTK_BOX (hbox38), label178, FALSE, FALSE, 0);

  _ = gtk_button_new ();
  gtk_widget_show (_);
  gtk_fixed_put (GTK_FIXED (fixed15), _, 640, 328);
  gtk_widget_set_size_request (_, 144, 32);

  alignment39 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment39);
  gtk_container_add (GTK_CONTAINER (_), alignment39);

  hbox39 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox39);
  gtk_container_add (GTK_CONTAINER (alignment39), hbox39);

  image83 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image83);
  gtk_box_pack_start (GTK_BOX (hbox39), image83, FALSE, FALSE, 0);

  label179 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label179);
  gtk_box_pack_start (GTK_BOX (hbox39), label179, FALSE, FALSE, 0);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("5000 habitants"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton1, 192, 232);
  gtk_widget_set_size_request (radiobutton1, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("10.001 \303\240 25.000 habitants "));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton3, 192, 296);
  gtk_widget_set_size_request (radiobutton3, 200, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("25.001 \303\240 50.000 habitants "));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton4, 192, 328);
  gtk_widget_set_size_request (radiobutton4, 200, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("50.001 \303\240 100.000 habitants "));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton5, 192, 360);
  gtk_widget_set_size_request (radiobutton5, 208, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("100.001 \303\240 500.000 habitants "));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton6, 192, 392);
  gtk_widget_set_size_request (radiobutton6, 232, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("plus que 500.000 habitants "));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton7, 192, 424);
  gtk_widget_set_size_request (radiobutton7, 224, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  label171 = gtk_label_new (_("<span color=\"purple\" ><b>ID</b></span>"));
  gtk_widget_show (label171);
  gtk_fixed_put (GTK_FIXED (fixed15), label171, 56, 72);
  gtk_widget_set_size_request (label171, 88, 32);
  gtk_label_set_use_markup (GTK_LABEL (label171), TRUE);

  label173 = gtk_label_new (_("<span color=\"purple\"  ><b>Date d'election</b></span>"));
  gtk_widget_show (label173);
  gtk_fixed_put (GTK_FIXED (fixed15), label173, 24, 152);
  gtk_widget_set_size_request (label173, 168, 40);
  gtk_label_set_use_markup (GTK_LABEL (label173), TRUE);

  label172 = gtk_label_new (_("<span color=\"purple\"  ><b>NbC</b></span>"));
  gtk_widget_show (label172);
  gtk_fixed_put (GTK_FIXED (fixed15), label172, 504, 168);
  gtk_widget_set_size_request (label172, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (label172), TRUE);

  label175 = gtk_label_new (_("<span color=\"purple\"  ><b>Nombre des habitants </b></span>"));
  gtk_widget_show (label175);
  gtk_fixed_put (GTK_FIXED (fixed15), label175, 8, 232);
  gtk_widget_set_size_request (label175, 184, 16);
  gtk_label_set_use_markup (GTK_LABEL (label175), TRUE);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("5001 \303\240 10.000 habitants"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton2, 192, 264);
  gtk_widget_set_size_request (radiobutton2, 200, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  label191 = gtk_label_new (_("<span color=\"purple\"  ><b>Municipalit\303\251</b></span>"));
  gtk_widget_show (label191);
  gtk_fixed_put (GTK_FIXED (fixed15), label191, 512, 72);
  gtk_widget_set_size_request (label191, 112, 40);
  gtk_label_set_use_markup (GTK_LABEL (label191), TRUE);

  label201 = gtk_label_new (_("<span color=\"brown\" font-size=\"19000\" ><b>Ajouter une election</b></span>"));
  gtk_widget_show (label201);
  gtk_fixed_put (GTK_FIXED (fixed15), label201, 280, 8);
  gtk_widget_set_size_request (label201, 312, 48);
  gtk_label_set_use_markup (GTK_LABEL (label201), TRUE);

  comboboxnbc = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxnbc);
  gtk_fixed_put (GTK_FIXED (fixed15), comboboxnbc, 648, 168);
  gtk_widget_set_size_request (comboboxnbc, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnbc), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnbc), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnbc), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnbc), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnbc), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnbc), _("40"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnbc), _("60"));

  comboboxnbh = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxnbh);
  gtk_fixed_put (GTK_FIXED (fixed15), comboboxnbh, 648, 80);
  gtk_widget_set_size_request (comboboxnbh, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnbh), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnbh), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnbh), _("Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnbh), _("Hammamet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnbh), _("Ben arous"));

  g_signal_connect ((gpointer) buttonMenu, "clicked",
                    G_CALLBACK (on_buttonMenu_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAjouter, "clicked",
                    G_CALLBACK (on_buttonAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) _, "clicked",
                    G_CALLBACK (on__annulerajout),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton44_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5, "toggled",
                    G_CALLBACK (on_radiobutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton6, "toggled",
                    G_CALLBACK (on_radiobutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton7, "toggled",
                    G_CALLBACK (on_radiobutton7_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAjoutelection, windowAjoutelection, "windowAjoutelection");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, entryId, "entryId");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, spinbuttonSkJours, "spinbuttonSkJours");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, spinbuttonSkMois, "spinbuttonSkMois");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, spinbuttonSkAnnees, "spinbuttonSkAnnees");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, buttonMenu, "buttonMenu");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, alignment40, "alignment40");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, hbox40, "hbox40");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, image84, "image84");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, label180, "label180");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, buttonAjouter, "buttonAjouter");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, alignment38, "alignment38");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, hbox38, "hbox38");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, image82, "image82");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, label178, "label178");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, _, "_");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, alignment39, "alignment39");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, hbox39, "hbox39");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, image83, "image83");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, label179, "label179");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, label171, "label171");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, label173, "label173");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, label172, "label172");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, label175, "label175");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, label191, "label191");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, label201, "label201");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, comboboxnbc, "comboboxnbc");
  GLADE_HOOKUP_OBJECT (windowAjoutelection, comboboxnbh, "comboboxnbh");

  return windowAjoutelection;
}

