/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *windowGestionelection;
  GtkWidget *windowAjoutSucc;
  GtkWidget *windowModifSucc;
  GtkWidget *windowSupSucc;
  GtkWidget *windowRemplir;
  GtkWidget *windowID;
  GtkWidget *windowModifierelection;
  GtkWidget *Modifierelection;
  GtkWidget *windowAjoutelection;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("pixmaps");

  //add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  windowGestionelection = create_windowGestionelection ();
  gtk_widget_show (windowGestionelection);
/*
  windowAjoutSucc = create_windowAjoutSucc ();
  gtk_widget_show (windowAjoutSucc);
  windowModifSucc = create_windowModifSucc ();
  gtk_widget_show (windowModifSucc);
  windowSupSucc = create_windowSupSucc ();
  gtk_widget_show (windowSupSucc);
  windowRemplir = create_windowRemplir ();
  gtk_widget_show (windowRemplir);
  windowID = create_windowID ();
  gtk_widget_show (windowID);
  windowModifierelection = create_windowModifierelection ();
  gtk_widget_show (windowModifierelection);
  Modifierelection = create_Modifierelection ();
  gtk_widget_show (Modifierelection);
  windowAjoutelection = create_windowAjoutelection ();
  gtk_widget_show (windowAjoutelection);
*/
  gtk_main ();
  return 0;
}

